apiVersion: v1
kind: Pod
metadata:
  name: driver
  labels:
    run: test-driver
spec:
  containers:
    - name: test-driver
      image: cosi-driver
      imagePullPolicy: IfNotPresent
      ports:
      - name: cosidriver
        containerPort: 9000
    - name: test-provisioner
      image: cosi-provisioner
      imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: test-driver
  labels:
    run: test-driver
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    run: test-driver
